# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73157bd0bf8f9a9f0daddc315ebec68c2f793faed710508d59a6c5db3adeaafd703a0b69d0fb92b590cdb3abd7c93918d6d13576cf5443c4357abc770e9fcc17

test:
  secret_key_base: f630f226eef2b92ae56d396c34a3fc48041bc8b80c27868fe0b90c954b2ef700b71dfb77d5bf53819a83099407fd16556ed58785f9eb794a21f8f4932d896238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
